# Generated by Django 3.2.7 on 2023-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50, null=True)),
                ('custName', models.CharField(max_length=50, null=True)),
                ('custPhone', models.CharField(max_length=50, null=True)),
                ('custEmail', models.CharField(max_length=50, null=True)),
                ('custMessage', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
